let method_1 = document.querySelector(".element");
console.log(method_1);
let method_2 = document.querySelector("#elzero");
console.log(method_2);
let method_3 = document.querySelector('[name = "js"]');
console.log(method_3);
let method_4 = document.querySelector("div");  
console.log(method_4);
let method_5 = document.querySelectorAll(".element")[0];
console.log(method_5);
let method_6 = document.querySelectorAll("#elzero")[0];  
console.log(method_6);
let method_7 = document.querySelectorAll(`[name = "js"]`)[0];  
console.log(method_7);
let method_8 = document.querySelectorAll(`div`)[0];  
console.log(method_8);
let method_9 = document.body.firstChild;  
console.log(method_9);
let method_10 = document.body.firstElementChild;  
console.log(method_10);
let method_11 = document.body.children[0];  
console.log(method_11);
let method_12 = document.getElementById("elzero");  
console.log(method_12);
let method_13 = document.getElementsByClassName("element")[0];  
console.log(method_13);
let method_14 = document.getElementsByTagName("div")[0];  
console.log(method_14);
let method_15 = document.body.childNodes[0];  
console.log(method_15);
